project = ../../../odm-k8s-bob-mode/projects/CrossBorderFraudDetection/CrossBorderFraudDetection
output = ../../../odm-k8s-bob-mode/projects/CrossBorderFraudDetection/CrossBorderFraudDetection/output
dep = deployment
xom-classpath = ../../../odm-k8s-bob-mode/projects/CrossBorderFraudDetection/cross-border-fraud-xom/cross-border-fraud-xom-1.0.0.jar